name=MicroboltOTA
version=1.0.0
author=Microbolt Robotics
maintainer=Microbolt Robotics
sentence=ESP32 OTA updates and Telnet logging.
paragraph=Simple OTA uploads and wireless serial monitor for ESP32 projects.
category=Communication
url=https://github.com/yourusername/MicroboltOTA
architectures=esp32